version: "3.6"
services:
  nacos1:
    image: nacos/nacos-server:latest
    hostname: "nacos1"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 2048M
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
     # - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    configs:
      - source: custom 
        target: /home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ../env/nacos-hostname.env
    depends_on:
      - mysql-master
      - mysql-slave
    networks:
      - my-swarm
  nacos2:
    image: nacos/nacos-server:latest
    hostname: "nacos2"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 2048M
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
     # - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    configs:
      - source: custom 
        target: /home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
      - "9556:9555"
    env_file:
      - ../env/nacos-hostname.env
    depends_on:
      - mysql-master
      - mysql-slave
    networks:
      - my-swarm
  nacos3:
    image: nacos/nacos-server:latest
    hostname: nacos3
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 2048M
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
     # - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    configs:
      - source: custom 
        target: /home/nacos/init.d/custom.properties
    ports:
      - "8850:8848"
      - "9557:9555"
    env_file:
      - ../env/nacos-hostname.env
    depends_on:
      - mysql-master
      - mysql-slave
    networks:
      - my-swarm
  mysql-master:
    hostname: mysql-master
    image: nacos/nacos-mysql-master:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    env_file:
      - ../env/mysql-common.env
      - ../env/mysql-master.env
    volumes:
      - ./mysql-master:/var/lib/mysql
    networks:
      - my-swarm
  mysql-slave:
    hostname: mysql-slave
    image: nacos/nacos-mysql-slave:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    env_file:
      - ../env/mysql-common.env
      - ../env/mysql-slave.env
    volumes:
      - ./mysql-slave:/var/lib/mysql
    depends_on:
      - mysql-master
    networks:
      - my-swarm
configs:
  custom:
    file: ./init.d/custom.properties
networks:
  my-swarm:
    external: true

